// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/usuarios": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "responses": {}
            }
        },
        "/usuarios/atualizar": {
            "put": {
                "description": "Passe um email de um usuario existente. Preencha somente os campos que quer atualizar.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome novo",
                        "name": "nome",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "E-mail atual",
                        "name": "emailAtual",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "E-mail novo",
                        "name": "emailNovo",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Senha atual",
                        "name": "senhaAtual",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Senha nova",
                        "name": "senhaNova",
                        "in": "path"
                    }
                ],
                "responses": {}
            }
        },
        "/usuarios/criar": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome",
                        "name": "nome",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "E-mail",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Senha",
                        "name": "senha",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:3429",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Projeto do Desafio Go CRUD",
	Description:      "Para saber mais leia o README.md",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
