basePath: /
definitions:
  controllers.usuarioCreate:
    properties:
      email:
        type: string
      nome:
        type: string
      senha:
        type: string
    type: object
  controllers.usuarioDelete:
    properties:
      id:
        type: integer
      senha:
        type: string
    type: object
  controllers.usuarioUpdate:
    properties:
      emailAtual:
        type: string
      emailNovo:
        type: string
      nome:
        type: string
      senhaAtual:
        type: string
      senhaNova:
        type: string
    type: object
host: localhost:3429
info:
  contact: {}
  description: Para saber mais leia o README.md
  title: Projeto do Desafio Go CRUD
paths:
  /usuarios:
    get:
      description: Lista todos os usuários.
      produces:
      - application/json
      responses: {}
      tags:
      - Usuarios
  /usuarios/atualizar:
    put:
      consumes:
      - application/json
      description: Passe um email de um usuario existente. Preencha somente os campos
        que quer atualizar.
      parameters:
      - description: Corpo JSON
        in: body
        name: JSON
        required: true
        schema:
          $ref: '#/definitions/controllers.usuarioUpdate'
      produces:
      - application/json
      responses: {}
      tags:
      - Usuarios
  /usuarios/criar:
    post:
      consumes:
      - application/json
      description: Cria um usuário.
      parameters:
      - description: Corpo JSON
        in: body
        name: JSON
        required: true
        schema:
          $ref: '#/definitions/controllers.usuarioCreate'
      produces:
      - application/json
      responses: {}
      tags:
      - Usuarios
  /usuarios/deletar:
    delete:
      consumes:
      - application/json
      description: Passe um ID de um usuário existente e sua senha para o deletar.
      parameters:
      - description: Corpo JSON
        in: body
        name: JSON
        required: true
        schema:
          $ref: '#/definitions/controllers.usuarioDelete'
      produces:
      - application/json
      responses: {}
      tags:
      - Usuarios
swagger: "2.0"
